name: Response Time CI

on:
  schedule:
    # Gera gráficos de tempo de resposta a cada hora
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  response-time:
    name: Gerar gráficos de tempo de resposta
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upptime — Generate response time graphs
        uses: upptime/uptime-monitor@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          command: response-time
