name: Update Template

on:
  schedule:
    # Atualiza o template do Upptime mensalmente
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update:
    name: Atualizar template Upptime
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Upptime — Update template
        uses: upptime/uptime-monitor@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          command: update-template
